.TH packlim 8
.SH NAME
.B packlim
\- a package manager
.SH SYNOPSIS
.B packlim
update|available|installed|install|remove|lock|source|purge [ARG]...
.SH DESCRIPTION
Manages software packages.
.TP
.B update
Fetch the list of available packages.
.TP
.B available
Lists available packages.
.TP
.B installed
Lists installed packages.
.TP
.B install
Installs a package.
.TP
.B remove
Removes a package.
.TP
.B lock
Prevent a package from being removed.
.TP
.B source
Runs a script.
.TP
.B purge
Removes downloaded files.
.SH FILES
.TP
.B /etc/packlim/pub_key
The public key used to verify digital signatures.
.TP
.B /var/packlim/downloaded
Downloaded packages.
.TP
.B /var/packlim/installed
Installed packages.
.TP
.B /var/packlim/lock
A lock file.
.SH "ENVIRONMENT VARIABLES"
.TP
.B REPO
The package repository URL.
.TP
.B PREFIX
The package installation directory.
.SH "SEE ALSO"
.B dir2pkg(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
