.TH packlim 8
.SH NAME
.B packlim
\- a package manager
.SH SYNOPSIS
.B packlim
{update | available | installed | install\ \fIname\fR... | remove\ \fIname\fR... | autoremove\ [\fIname\fR...] | lock\ \fIname\fR | source \fIscript\fR | purge}
.SH DESCRIPTION
Manages software packages.
.TP
.B update
Fetch the list of available packages.
.TP
.B available
List available packages.
.TP
.B installed
List installed packages.
.TP
.B install
Install packages.
.TP
.B remove
Remove packages.
.TP
.B autoremove
Optionally remove packages, then automatically remove all unneeded packages.
.TP
.B lock
Prevent a package from being removed.
.TP
.B source
Run a script.
.TP
.B purge
Removes downloaded files.
.SH FILES
.TP
.B /etc/packlim/pub_key
The public key used to verify digital signatures.
.TP
.B /var/packlim/downloaded
Downloaded packages.
.TP
.B /var/packlim/installed
Installed packages.
.TP
.B /var/packlim/lock
A lock file.
.SH "ENVIRONMENT VARIABLES"
.TP
.B REPO
The package repository URL.
.TP
.B PREFIX
The package installation directory.
.SH "SEE ALSO"
.B dir2pkg(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
