#!/bin/sh

if [ 4 -ne $# ]
then
	echo "Usage: $0 TAR PRIVATE PUBLIC OUTPUT" 1>&2
	exit 1
fi

# copy the archive
cp -f "$1" "$4"

# append packlad's magic number (0x686a6b6c)
echo -n "hjkl" >> "$4"

# sign the archive using Ed25519 and append the 64-byte signature
pkgsign "$2" "$3" "$1" >> "$4"
if [ 0 -ne $? ]
then
	rm -f "$4"
	exit 1
fi
