#!/bin/sh

if [ 4 -ne $# ]
then
	echo "Usage: $0 TAR PRIVATE PUBLIC OUTPUT" 1>&2
	exit 1
fi

# copy the archive
cp -f "$1" "$4"

# append packlim's magic number (0x686a6b6c)
echo -n hjkl >> "$4"

# append a 64-byte Ed25519 signature to the archive
ed25519 -s "$1" "$2" "$3" >> "$4"
if [ 0 -ne $? ]
then
	rm -f "$4"
	exit 1
fi
